# Generated by Django 4.2.3 on 2023-07-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('fono', models.CharField(max_length=10)),
                ('identificador', models.CharField(max_length=20)),
                ('numIdentificador', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('idProductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreContacto', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('razonSocial', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=25)),
                ('descripcionProducto', models.TextField(blank=True)),
                ('precioProducto', models.PositiveIntegerField()),
                ('imagenProducto', models.ImageField(upload_to='productos/')),
                ('stockProducto', models.PositiveIntegerField()),
                ('idProductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teloenvio.productor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPedido', models.DateField(auto_now_add=True)),
                ('direccionEntrega', models.CharField(max_length=100)),
                ('estadoPedido', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En preparación', 'En preparación'), ('En Despacho', 'En Despacho'), ('Entregado', 'Entregado')], default='Pendiente')),
                ('formaPago', models.CharField(choices=[('TF', 'Transferencia'), ('TC', 'Tarjeta de Crédito'), ('TD', 'Tarjeta de Débito')])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teloenvio.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teloenvio.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teloenvio.producto')),
            ],
        ),
    ]
